#!/usr/bin/env python3

"""
    Bagels is a deduction game in which the player tries to guess a random
    three-digit number (with no repeating digits) generated by the computer.
    After each guess, the computer gives the player three types of clues:

    Bagels None of the three digits guessed is in the secret number.

    Pico One of the digits is in the secret number, but the guess has the
    digit in the wrong place.

    Fermi The guess has a correct digit in the correct place.

    The computer can give multiple clues, which are sorted in alphabetical
    order. If the secret number is 456 and the player’s guess is 546, the
    clues would be “fermi pico pico.” The “fermi” is from the 6 and
    “pico pico” are from the 4 and 5.

    2018/08/11 17:27:04 Сделал , но не похоже на оригинал
"""

import random

# ПОДГОТОВКА "СЕКРЕТНОГО" ЧИСЛА
#создать список (10 элементов (0..9)    #благодаря подсказки
num = list( range(10))
# shuffle - перемешать, тасовать :)
# А кто-то говорит что его ребенку не нужен английский
random.shuffle(num)
secretNum = ( str(num[0]) + str(num[1]) + str(num[2]) )

print("""You tries to guess a random  three-digit number (with no
    repeating digits) generated by the computer.
    
    Bagels None of the three digits guessed is in the secret number.

    Pico One of the digits is in the secret number, but the guess has the
    digit in the wrong place.

    Fermi The guess has a correct digit in the correct place. """)
    
while True:
    checkList = ['_Bagels_','_Bagels_','_Bagels_']        
    guess = input('Input your number ')
    #провепка числа (сдаётся мне её можно сделать по другому
    if len(guess) == 3 and guess.isdigit() :
        for i in range(3) :
            for j in range(3) :
                if guess[i] == secretNum[j] :
                    if i == j :
                        checkList[i] = '_Fermi_'
                    else :
                        checkList[i] = '_Pico_'
    else :
        print(' Please, input three-digit number only')
        continue

    print( checkList )
    if checkList == ['_Fermi_', '_Fermi_','_Fermi_'] :
        print(' You Won congrulation')
        break
        
print('Secret number =>' , secretNum )
